// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    FavorCard: typeof import('./components/FavorCard.vue')['default']
    HotSpotCard: typeof import('./components/HotSpotCard.vue')['default']
    HotSpotTable: typeof import('./components/HotSpotTable.vue')['default']
    RankListItem: typeof import('./components/RankListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
